apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::980165832341:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1RL12I53CHJK4
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::980165832341::role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-06T17:45:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1841"
  uid: 1a91aa10-3a9e-4e9b-a598-8106f11a6464
